name: Manual UPD preprod deploy
on:
  workflow_call:
    inputs:
      update_simbioz:
        required: true
        type: boolean
      base_update:
        required: false
        type: boolean
      SERVER_ADDR:
        required: true
        type: string
      SERVER_USER:
        required: true
        type: string
      SERVER_PORT:
        required: true
        type: string
      MAIN_PATH:
        required: true
        type: string
      CUSTOM_PATH:
        required: true
        type: string
      ODOO_SERVICE:
        required: true
        type: string
      ODOO_USER:
        required: true
        type: string
      ODOO_URI:
        required: true
        type: string
      ODOO_DB:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true
      ODOO_PASSWORD:
        required: true
env:
  MAIN_PATH: ${{inputs.MAIN_PATH}}
  ODOO_CONFIG: ${{inputs.MAIN_PATH}}/config_local/odoo-server.conf
  ODOO_DB: ${{inputs.ODOO_DB}}
  SERVER_USER: ${{inputs.SERVER_USER}}
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check variables
        run: |
          echo "=== CHECKING INPUTS ==="
          if [[ -z "${{inputs.SERVER_ADDR}}" ]]; then
            echo "SERVER_ADDR is not set"
            exit 100
          fi
          if [[ -z "${{inputs.SERVER_USER}}" ]]; then
            echo "SERVER_USER is not set"
            exit 100
          fi
          if [[ -z "${{inputs.MAIN_PATH}}" ]]; then
            echo "MAIN_PATH is not set"
            exit 100
          fi
          if [[ -z "${{inputs.ODOO_SERVICE}}" ]]; then
            echo "ODOO_SERVICE is not set"
            exit 100
          fi
          if [[ -z "${{inputs.ODOO_USER}}" ]]; then
            echo "ODOO_USER is not set"
            exit 100
          fi
          if [[ -z "${{inputs.ODOO_URI}}" ]]; then
            echo "ODOO_URI is not set"
            exit 100
          fi
          if [[ -z "${{inputs.ODOO_DB}}" ]]; then
            echo "ODOO_DB is not set"
            exit 100
          fi
          echo "=== END CHECKING INPUTS ==="
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: qdnick/ci_cd_workflows
          ref: 'main'
          path: ci_cd_tools
      - name: Install Python
        if: ${{!inputs.base_update}}
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.18'
      - name: Create SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{inputs.SERVER_ADDR}} > ~/.ssh/known_hosts
          cat >~/.ssh/config <<EOF
          Host deploy
            HostName ${{inputs.SERVER_ADDR}}
            User $SERVER_USER
            Port ${{inputs.SERVER_PORT}}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
          ssh -T deploy > /dev/null
          echo "#!/bin/bash" > ~/update_script.sh
      - name: Update from SIMBIOZ repo - prepare
        if: ${{inputs.update_simbioz}}
        run: |
          cat <<EOF >> ~/update_script.sh
          echo "=== UPDATING SIMBIOZ REPOs ==="
          cd ${{inputs.MAIN_PATH}}
          git submodule foreach --recursive git config --local --replace-all safe.directory '*'
          git submodule foreach --recursive git checkout main
          git submodule foreach --recursive 'git add . && git diff-index --quiet HEAD || (git stash && git stash drop)'
          git submodule foreach --recursive git reset --hard
          git submodule foreach --recursive git pull
          sh odoo_set_icons.sh || true
          EOF
      - name: Update from BIKO repo - prepare
        env:
          PTH_STRING: ${{'$PTH'}}
        run: |
          cat <<EOF >> ~/update_script.sh
          echo "=== UPDATING BIKO REPOs ==="
          if [[ -n "${{inputs.CUSTOM_PATH}}" ]]; then
            for PTH in {${{inputs.CUSTOM_PATH}}}
            do
              if [[ -d "$PTH_STRING" ]]; then
                cd "$PTH_STRING"
                echo "Current directory: " && pwd
                git checkout dev
                if [[ $? -eq 0 ]]; then
                  git add . && git diff-index --quiet HEAD || (git stash && git stash drop)
                  git reset --hard
                  git pull
                fi
              else
                echo "No folder $PTH_STRING"
              fi
            done
          else
            echo "NO CUSTOM FOLDERS SPECIFIED"
          fi
          EOF
      - name: Soft update (only changes)
        if: ${{!inputs.base_update}}
        run: |
          echo "=== GET DATABASE LIST ==="
          ssh deploy "sudo systemctl restart ${{inputs.ODOO_SERVICE}} && sleep 10"
          if [[ $ODOO_DB == -* ]]; then
            DB_RESULT=$(ssh deploy "sudo -u $SERVER_USER bash -c 'source $MAIN_PATH/venv/bin/activate && click-odoo-listdb -c \"$ODOO_CONFIG\"'")
          else
            DB_RESULT=$ODOO_DB
          fi
          echo "=== DATABASES ==="
          echo "$DB_RESULT"
          for db in $DB_RESULT; do
            echo "=== UPDATING DATABASE $db ==="
            ssh -o TCPKeepAlive=yes -o ServerAliveCountMax=100 -o ServerAliveInterval=60 deploy "sudo -u $SERVER_USER bash -c 'source $MAIN_PATH/venv/bin/activate && click-odoo-update -c \"$ODOO_CONFIG\" -d \"$db\" --watcher-max-seconds 0 --log-level info'"
          done
      - name: Hard update (base module)
        if: ${{inputs.base_update}}
        run: |
          echo "=== STOPPING ODOO ==="
          ssh deploy "sudo systemctl stop ${{inputs.ODOO_SERVICE}} && sleep 10"
          if [[ $ODOO_DB == -* ]]; then
            DB_RESULT=$(ssh deploy "sudo -u $SERVER_USER bash -c 'source $MAIN_PATH/venv/bin/activate && click-odoo-listdb -c \"$ODOO_CONFIG\"'")
          else
            DB_RESULT=$ODOO_DB
          fi
          echo "=== DATABASES ==="
          echo "$DB_RESULT"
          for db in $DB_RESULT; do
            echo "=== UPDATING DATABASE $db ==="
            ssh -o TCPKeepAlive=yes -o ServerAliveCountMax=100 -o ServerAliveInterval=60 -p ${{inputs.SERVER_PORT}} ${{inputs.SERVER_USER}}@${{inputs.SERVER_ADDR}} "sudo -u $SERVER_USER bash -c 'source $MAIN_PATH/venv/bin/activate && click-odoo-update -c \"$ODOO_CONFIG\" -d \"$db\" --update-all --watcher-max-seconds 0 --log-level info'"
            done
          ssh deploy "sudo systemctl start ${{inputs.ODOO_SERVICE}} && sleep 10"
          echo "=== SHOW STATUS ODOO ==="
          ssh deploy sudo systemctl status ${{inputs.ODOO_SERVICE}}
